# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run the python code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      labels: ubuntu-latest
    environment: "steady"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        RUN apt-get update --fix-missing && apt-get install -y --fix-missing build-essential
        python -m pip install --upgrade pip setuptools
        pip install crewai "crewai[tools]" markdown
    - name: Run the crew
      run: |
        python main.py
      env: 
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
        OPENAI_MODEL_NAME:  ${{ secrets.OPENAI_MODEL_NAME }}
